import Head from 'next/head'
import { useEffect, useState } from "react";
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {supabase} from '../utils/ideas';

export default function Home() {
  
  const [ideas,setIdeas] = useState([])
  const [idea,setIdea] = useState({title: '', description: ""})
  const {title, description} = idea
  const [reload,setReload] = useState(false)
  

  useEffect(()=>{
    fetchIdeas()
  },[reload])

  async function fetchIdeas() {
    const {data} = await supabase.from('Ideas').select()
    setIdeas(data)
  }

  async function createIdea() {
    setReload(prev => !prev)
    const {data} = await supabase.from('Ideas').insert([{title, description}],{ upsert: false }).single()
    setIdea({title:"",description: ""})
  }

  const inputHandle = (e,i)=> {
    if ( i == 1 ) setIdea(prev => ({...prev, title:e}))
    else if (i == 2) setIdea(prev => ({...prev, description:e}))
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>IDEAS</h1>
      <h4>Upload your best ideas to the world</h4>
    <div className='container'>
      <h2>INSERT</h2>
      <input
        placeholder='Title'
        value={idea.title}
        onChange={ (e,i)=> inputHandle(e.target.value,1)}
      />
      <input
        placeholder='Description'
        value={idea.description}
        onChange={ (e,i)=> inputHandle(e.target.value,2)}
      />
      <button
        onClick={createIdea}>Create Idea</button>
    </div>
    <div className='item-container'>
      {
        ideas.length == 0 ?
        <div class="spinner"></div> :
        ideas.map(idea => (
          <div className='item' key={idea.id}>
            <h4>{idea.title}</h4>
            <h6>{idea.description}</h6>
          </div>)
        )
      }
    </div>
    </div>
  )
}
