import Head from 'next/head'
import { useEffect, useState } from "react";
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {supabase} from '../utils/ideas';

export default function Home() {
  
  const [ideas,setIdeas] = useState([])
  const [idea,setIdea] = useState({title: '', description: ""})
  const {title, description} = idea

  useEffect(()=>{
    fetchIdeas()
  },[])

  async function fetchIdeas() {
    const {data} = await supabase.from('Ideas').select()
    setIdeas(data)
  }

  async function createIdea() {
    const {data} = await supabase.from('Ideas').insert([{title, description}]).single()
    setIdea({title:"",description: ""})
  }
  console.log(ideas);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>Insert</h2>
      <input></input>
      <input></input>
    </div>
  )
}
